### ISSUE TITLE
Sass compiler not working

### ISSUE THREAD

**Issue by mrzool** [jekyll/jekyll-help#104]
Jekyll seems to ignore my `*.scss` files and doesn't compile any CSS.

This is my project:

```
.
├── LICENSE
├── README.md
├── _config.yml
├── _scss
│   ├── _borders.scss
│   ├── _button-themes.scss
│   ├── _buttons.scss
│   ├── _colors.scss
│   ├── _form-themes.scss
│   ├── _forms.scss
│   ├── _grid.scss
│   ├── _lists.scss
│   ├── _margins.scss
│   ├── _nav-themes.scss
│   ├── _navs.scss
│   ├── _padding.scss
│   ├── _positions.scss
│   ├── _reset.scss
│   ├── _table-object.scss
│   ├── _table-themes.scss
│   ├── _tables.scss
│   ├── _theme.scss
│   ├── _type.scss
│   ├── _utilities.scss
│   ├── _variables.scss
│   ├── basscss-lite.scss
│   └── basscss.scss
├── css
├── gulpfile.js
├── index.html
├── js
│   ├── app.js
│   └── min
│       └── app.js
└── package.json

4 directories, 31 files
```

This is my `_config.yml`:

```
# Site settings
title: trim-jekyll-basscss
email: your-email@domain.com
description: "Combinig Jekyll, Trim and BassCSS"
baseurl: "/"
url: "http://https://github.com/mrzool/trim-jekyll-basscss"
twitter_username: __zool
github_username:  mrzool

# Build settings
markdown: kramdown
permalink: pretty

# Sass settings
sass:
    sass_dir: _scss
    style: :compressed
```

The Sass on my system: `Sass 3.3.11 (Maptastic Maple)`
Jekyll: `jekyll 2.1.1`

Am I doing something wrong?

Thanks for any help.
