### ISSUE TITLE
type: "posts" in _config.yml default block seems not working

### ISSUE THREAD

**Issue by notyy** [jekyll/jekyll-help#136]
hi, I am trying to create blog site in github page. the site source is in https://github.com/notyy/notyy.github.io

I specified default values in _config.yml

``` YAML
defaults:
  -
    scope:
      path: ""
      # type: "posts"
    values:
      layout: "post"
      encoding: utf-8
```

if I uncomment the line of `type: "posts"` then, the layout and encoding is lost.
