### ISSUE TITLE
Mangled quotation marks

### ISSUE THREAD

**Issue by kentcb** [jekyll/jekyll-help#154]
Hi,

I'm just getting started with Jekyll. I've run into an issue where my quotation marks are being mistransformed. Presumably this is an encoding issue, but I've explicitly set my encoding to UTF-8 in my *_config.yml*:
```
exclude: [ Gemfile ]
encoding: "UTF-8"

defaults:
  -
    scope:
      path: ""          # all files
      type: "posts"     # only posts though
    values:
      layout: "default"
```
I've also double-checked that the file in question is being saved as UTF-8. I tried two different text editors to be sure.

Here's the input file (markdown):
```
---
title: A test
---

Here are some 'single quotes'. Here are some "double quotes".
```
And here is what I see when I browse to the generated site:

![screen shot 2014-09-19 at 12 15 54 pm](https://cloud.githubusercontent.com/assets/1901832/4330107/2de6e124-3fa7-11e4-9f79-c57889ad3dc0.png)

Can anyone tell me how to rectify this?

Thanks
