### ISSUE TITLE
Theme settings in config or data?

### ISSUE THREAD

**Issue by doktorbro** [jekyll/jekyll-help#21]
I write a customizable theme for Jekyll. Call it `theme`. I see two places where the user can place her settings:
1. `_config.yml`
   
   ``` yml
   theme:
     option1: value1
     option2: value2
   ```
   
   Then I access the settings via `site.theme`.
2. `_data/theme.yml`
   
   ``` yml
   option1: value1
   option2: value2
   ```
   
   Then I access the settings via `site.data.theme`.

Which one is better and why?
