### ISSUE TITLE
URLs not being properly formatted - contain commas

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll-help#227]
Hi

I have two questions (I have checked the docs and other issues but cannot find a solution to this).

1. I have created separate layout files (in `_layouts/`) for a default site-wide page style, and non-discussion posts and discussion posts (posts with Disqus comments enabled).  Specifically, pages follow the default layout specified in `default.html` which is standard, and non-discussion posts follow the standard `post.html` layout.  But the `discussion_posts` style were defined in `_config.yml` in the following way:
```
    defaults:  
    -
      scope:
        path: "/_posts/"
        type: "posts"
      values:
        layout: "discussion_posts"
        author: "Sandeep Murthy"
    -    
      scope:
        path: "."
        type: "pages"
      values:
        layout: "default"
        author: "Sandeep Murthy"
```
I'm not quite clear about the path key?  I am trying to specify a relative path (relative to the root of the repo) but I am not quite clear if this is causing my problem.  This may be linked to how the URLs are appearing incorrectly.  For example, my `index.html` contains a list of posts, this is generated by liquid code which loops over `site.posts`. The code is

    <ul class="post-list">
       {% for post in site.posts %}
         <li>
           <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>

           <h2>
             <a class="post-link" href="{{ site.url }}/{{ post.url }}"#disqus_thread>{{ post.title }}</a>
           </h2>
         </li>
       {% endfor %}
     </ul>

The `site.url` is set to `http://localhost:4000` in `_config.yml` when I'm testing the site locally.  This code displays the posts (there is only one right now) as

    http://localhost:4000//blog,/first/post,/jekyll,/codefree,/2015/2015/01/01/first-post.html

The post name is `2015-01-01-first-post.md`, which exists in the root of the repo, and as you can see above, there are commas separating them.

Why is this happening?  Is there a simpler way of outputting the URLs?  Thanks in advance.
