### ISSUE TITLE
Front matter defaults for collection's documents in subfolders

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-help#237]
Hi there,

I would like to organize collection's documents in subfolders and assign them different categories through front matter defaults. I have the following structure:

````
_kb
    - category1
        - article1.md
    - category2
        - article2.md
````

 In my `_config.yml` file I have:

````
# Collections
collections:
  kb:
    output: true
    permalink: /kb/:name/

# Defaults
defaults:
  -
    scope:
      path: "_kb/category1/"
      type: "kb"
    values:
      category: "category1"
  -
    scope:
      path: "_kb/category2/"
      type: "kb"
    values:
      category: "category2"
````

But this doesn't work. Any idea how I can assign different categories to documents in different subfolders through front-matter defaults?
