### ISSUE TITLE
Using config defaults for more than _posts

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll-help#297]
For some reason, I can only get my Jekyll defaults to work, when `path: “”`; if I do anything else, it breaks cf. hafniatimes/issues#13. And by break, I mean that the defaults just don’t seem to apply. Currently, I have to either define the values explicitly in the front matter or hardcode the permalinks.

The config file is [here][config], but here is the relevant part:

```yaml
defaults:
    -
        scope:
            path: “” # breaks if `path: _posts`
            type: "posts"
        values: &en_defaults
            layout: "post"
            author: "ndarville"
            lang: "en"
            categories: "articles"
    -
        scope: # busted
            path: "_posts/da"
        values: &da_defaults
            lang: "da"
            categories:
                - "da"
                - "articles"
#   - # Redundant when top scope path is ""
#       scope: # busted
#           path: "_drafts"
#       values: *en_defaults
    -
        scope: # busted
            path: "_drafts/da"
        values: *da_defaults
```

The top-most scope works—but breaks if I use `_posts` (or anything) instead of `””` as the path. Maybe I’m misunderstanding how the defaults work.

The idea is to have two types of posts:

* English posts/drafts where `lang: en` and `categories: articles`
* Danish posts/drafts where `lang: da` and `categories: [da, articles]`

Other example configs haven’t solved it for me either, so maybe someone here can figure out what’s up.

[config]: https://github.com/hafniatimes/hafniatimes.github.io/blob/e33b5c492b4e2c16942a98fd214cc63310342282/_config.yml#L29-L54
