### ISSUE TITLE
Front Matter defaults: Use categories in scope?

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll-help#45]
Is it possible to use categories as scope for Front Matter defaults?

```
  # all files with the category `portfolio` have the layout `post--portfolio`
  -
    scope:
      path: ""
      category: "portfolio" # Doesn't work.
    values:
      layout: "post--portfolio"
```
