### ISSUE TITLE
Confused by YAML Matter Defaults

### ISSUE THREAD

**Issue by trans** [jekyll/jekyll-help#83]
I don't understand how one is supposed to use YAML matter defaults. In the example given (reproduced below), the scope is listed as `path: "about/blog"` and `type: "post"`. But all posts are stored in one place `_posts`. So is `about/blog` the _destination_ somehow? But how would a blog post end up in `about/blog` when they almost certainly end up in `:year/:month/:day/...` ?

```
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "my-site"
  -
    scope:
      path: "about/blog"
      type: "post"
    values:
      layout: "meta-blog" # overrides previous default layout
      author: "Dr. Hyde"
```
